---
version: "3.3"

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.local
    image: dcrawl:1.0.0
    environment: &env
      DATABASE_HOSTNAME: postgres
      DATABASE_USERNAME: elixir
      DATABASE_PASSWORD: elixir
    volumes:
      - .:/app:cached
      - asdf:/root/.asdf
      - build:/app/_build
      - static:/app/priv/static
      - deps:/app/deps
      - node:/app/assets/node
#      - .docker/.irb_history:/root/.irb_history
#      - .docker/.bash_history:/root/.bash_history
#      - .docker/.byebug_history:/app/.byebug_history

  init:
    <<: *app
    entrypoint: '.docker/init.sh'

  dcrawl:
    <<: *app
    command:
      - mix
      - phx.server
    ports:
      - "4000:4000"
    depends_on:
      - init
      - postgres

  postgres:
    image: "postgres:12"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: elixir
      POSTGRES_PASSWORD: elixir
    ports:
      - 5432

volumes:
  asdf:
  build:
  deps:
  node:
  postgres:
  static:
