defmodule DungeonCrawl.DungeonInstances.Dungeon do
  use Ecto.Schema
  import Ecto.Changeset

  alias DungeonCrawl.TileTemplates.TileTemplate

  schema "dungeon_instances" do
    field :autogenerated, :boolean, default: false
    field :host_name, :string
    field :name, :string
    field :state, DungeonCrawl.EctoStateValueMap, default: %{}
    field :passcode, :string
    field :is_private, :boolean, default: false

    belongs_to :dungeon, DungeonCrawl.Dungeons.Dungeon
    has_many :levels, DungeonCrawl.DungeonInstances.Level, on_delete: :delete_all, foreign_key: :dungeon_instance_id
    has_many :level_headers, DungeonCrawl.DungeonInstances.LevelHeader, on_delete: :delete_all, foreign_key: :dungeon_instance_id
    has_many :locations, through: [:levels, :tiles, :player_location], on_delete: :delete_all
    has_many :saves, through: [:levels, :saves], on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(dungeon_instance, attrs) do
    # Probably don't need all these validations as it will copy them from the dungeon, which already has these validations
    dungeon_instance
    |> cast(attrs, [:name, :dungeon_id, :state, :autogenerated, :host_name, :is_private])
    |> cast_assoc(:levels)
    |> validate_length(:name, max: 32)
    |> validate_required([:name, :dungeon_id])
    |> TileTemplate.validate_state_values
    |> _generate_passcode()
  end

  defp _generate_passcode(changeset) do
    case changeset do
      %Ecto.Changeset{data: %{passcode: passcode}} when not is_nil(passcode) ->
        changeset
      %Ecto.Changeset{valid?: true} ->
        passcode = :crypto.strong_rand_bytes(4) |> Base.encode16 |> binary_part(0, 8)
        put_change(changeset, :passcode, passcode)
      _ ->
        changeset
    end
  end
end
