defmodule DungeonCrawlWeb.CrawlerTest do
  use DungeonCrawlWeb.ChannelCase

  alias DungeonCrawlWeb.DungeonChannel
  alias DungeonCrawlWeb.Crawler
  alias DungeonCrawl.Player

  alias DungeonCrawl.DungeonProcesses.{Instances, InstanceProcess, InstanceRegistry}

  test "join_and_broadcast/2 joining a dungeon" do
    dungeon = insert_autogenerated_dungeon()
    assert %Player.Location{} = location = Repo.preload(Crawler.join_and_broadcast(dungeon, "itsmehash"), :map_tile)

    # It registers the player location
    {:ok, instance} = InstanceRegistry.lookup_or_create(DungeonInstanceRegistry, location.map_tile.map_instance_id)
    location_map_tile_id = location.map_tile.id
    assert %Instances{player_locations: %{^location_map_tile_id => ^location}} = InstanceProcess.get_state(instance)

    # cleanup
    InstanceRegistry.remove(DungeonInstanceRegistry, location.map_tile.map_instance_id)
  end

  test "join_and_broadcast/2 joining an instance" do
    instance = insert_autogenerated_dungeon_instance()
    instance_id = instance.id
    {:ok, _, _socket} =
      socket("user_id_hash", %{user_id_hash: "itsmehash"})
      |> subscribe_and_join(DungeonChannel, "dungeons:#{instance.id}")
    
    assert %Player.Location{} = location = Repo.preload(Crawler.join_and_broadcast(instance, "itsmehash"), :map_tile)

    assert_broadcast "tile_changes", payload
    assert %{tiles: [%{row: location.map_tile.row, col: location.map_tile.col, rendering: "<div>@</div>"}]} == payload

    # It registers the player location
    {:ok, instance} = InstanceRegistry.lookup_or_create(DungeonInstanceRegistry, instance.id)
    location_map_tile_id = location.map_tile.id
    assert %Instances{player_locations: %{^location_map_tile_id => ^location}} = InstanceProcess.get_state(instance)

    # cleanup
    InstanceRegistry.remove(DungeonInstanceRegistry, instance_id)
  end

  test "leave_and_broadcast" do
    instance = insert_autogenerated_dungeon_instance(%{}, true)
    location = insert_player_location(%{map_instance_id: instance.id, row: 1, user_id_hash: "itsmehash"})
    location2 = insert_player_location(%{map_instance_id: instance.id, row: 2, user_id_hash: "someoneelsetokeeptheinstance"})
    location2_id = location2.map_tile_instance_id
    instance_id = instance.id

    {:ok, _, _socket} =
      socket("user_id_hash", %{user_id_hash: "itsmehash"})
      |> subscribe_and_join(DungeonChannel, "dungeons:#{instance.id}")
    
    assert %Player.Location{} = location = Repo.preload(Crawler.leave_and_broadcast(location), :map_tile)

    assert_broadcast "tile_changes", payload
    assert %{tiles: [%{row: location.map_tile.row, col: location.map_tile.col, rendering: "<div>.</div>"}]} == payload

    # It unregisters the player location
    {:ok, instance} = InstanceRegistry.lookup_or_create(DungeonInstanceRegistry, instance.id)
    assert %{^location2_id => %{user_id_hash: "someoneelsetokeeptheinstance"}} = InstanceProcess.get_state(instance).player_locations

    # cleanup
    InstanceRegistry.remove(DungeonInstanceRegistry, instance_id)
  end
end
