# Script for populating the database. You can run it as:
#
#     mix run priv/repo/joinable_dungeon_seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     DungeonCrawl.Repo.insert!(%DungeonCrawl.SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias DungeonCrawl.Repo
alias DungeonCrawl.{Dungeon,DungeonGenerator}

import Ecto.Changeset

IO.puts "Generating rooms dungeon"
{:ok, %{dungeon: rooms_dungeon}} = Dungeon.generate_map(DungeonGenerator, %{name: "Seeded Joinable Dungeon"})
rooms_dungeon |> cast(%{autogenerated: false}, [:autogenerated]) |> Repo.update!
IO.puts "Done"
