# Script for populating the database. You can run it as:
#
#     mix run priv/repo/joinable_dungeon_seeds.exs
#
# This doesn't need to be run, as dungeons can be autogenerated from the crawl page, as well as
# when creating a new dungeon - which allows you to select the map generator to use.

alias DungeonCrawl.{Dungeons,MapGenerators}

IO.puts "Generating rooms dungeon"
Dungeons.generate_dungeon(MapGenerators.ConnectedRooms,
                          %{autogenerated: false, active: true, name: "Seeded Joinable Dungeon"},
                          %{width: 40, height: 20})
IO.puts "Done"
