defmodule DungeonCrawlWeb.TestHelpers do
  alias DungeonCrawl.Repo

  def insert_user(attrs \\ %{}) do
    changes = Map.merge(%{
      name: "Some User",
      username: "user#{Base.encode16(:crypto.rand_bytes(8))}",
      password: "secretsauce",
    }, attrs)

    %DungeonCrawl.Account.User{}
    |> DungeonCrawl.Account.User.admin_changeset(changes)
    |> DungeonCrawl.Account.User.put_user_id_hash(:base64.encode(:crypto.strong_rand_bytes(24)))
    |> Repo.insert!()
  end

  def insert_autogenerated_dungeon(attrs \\ %{}) do
    changes = Map.merge(%{
      name: "Autogenerated",
      height: 20,
      width: 20
    }, attrs)

    {:ok, %{dungeon: dungeon}} = DungeonCrawl.Dungeon.generate_map(DungeonCrawl.DungeonGenerator.TestRooms, changes)
    dungeon
  end

  def insert_player_location(attrs \\ %{}) do
    changes = Map.merge(%{
      row: 3,
      col: 1,
      user_id_hash: "good_hash"
    }, attrs)

    %DungeonCrawlWeb.PlayerLocation{}
    |> DungeonCrawlWeb.PlayerLocation.changeset(changes)
    |> Repo.insert!()
  end
end
