defmodule DungeonCrawlWeb.TestHelpers do
  alias DungeonCrawl.Repo
  alias DungeonCrawl.TileTemplates

  def insert_user(attrs \\ %{}) do
    changes = Map.merge(%{
      name: "Some User",
      username: "user#{Base.encode16(:crypto.rand_bytes(8))}",
      password: "secretsauce",
    }, attrs)

    %DungeonCrawl.Account.User{}
    |> DungeonCrawl.Account.User.admin_changeset(changes)
    |> DungeonCrawl.Account.User.put_user_id_hash(:base64.encode(:crypto.strong_rand_bytes(24)))
    |> Repo.insert!()
  end

  def insert_tile_template(attrs \\ %{}) do
    changes= Map.merge(%{
      name: "Floor",
      description: "A dusty floor",
      character: ".",
      responders: "{move: {:ok}}"
    }, attrs)

    {:ok, tile_template} = TileTemplates.create_tile_template(changes)
    tile_template
  end

  def insert_openable_closable_tile_template_pair() do
    open_door = insert_tile_template(%{name: "open_door", character: "'"})
    closed_door = insert_tile_template(%{name: "open_door", character: "+"})

    {:ok, open_door}   = TileTemplates.update_tile_template(open_door, %{responders: "{move: {:ok}, close: {:ok, replace: [#{closed_door.id}]}}"})
    {:ok, closed_door} = TileTemplates.update_tile_template(closed_door, %{responders: "{open: {:ok, replace: [#{open_door.id}]}}"})
    {open_door, closed_door}
  end

  def insert_autogenerated_dungeon(attrs \\ %{}) do
    changes = Map.merge(%{
      name: "Autogenerated",
      height: 20,
      width: 20
    }, attrs)

    {:ok, %{dungeon: dungeon}} = DungeonCrawl.Dungeon.generate_map(DungeonCrawl.DungeonGenerator.TestRooms, changes)
    dungeon
  end

  def insert_stubbed_dungeon(attrs \\ %{}, tiles \\ []) do
    changes = Map.merge(%DungeonCrawl.Dungeon.Map{
      name: "Stubbed",
      height: 20,
      width: 20
    }, attrs)

    dungeon = DungeonCrawl.Dungeon.change_map(changes) |> Repo.insert!
    Repo.insert_all(DungeonCrawl.Dungeon.MapTile, _tile_hydrator(dungeon.id, tiles))
    dungeon
  end

  defp _tile_hydrator(dungeon_id, tiles) do
    tiles
    |> Enum.map(fn(t) -> %{dungeon_id: dungeon_id, row: t.row, col: t.col, tile_template_id: t.tile_template_id} end)
  end

  def insert_player_location(attrs \\ %{}) do
    changes = Map.merge(%{
      row: 3,
      col: 1,
      user_id_hash: "good_hash"
    }, attrs)

    DungeonCrawl.Player.create_location!(changes)
  end
end
