defmodule DungeonCrawl.GamesFixtures do
  @moduledoc """
  This module defines test helpers for creating
  entities via the `DungeonCrawl.Games` context.
  """

  import DungeonCrawlWeb.TestHelpers

  alias DungeonCrawl.Games
  alias DungeonCrawl.Repo
  alias DungeonCrawl.Player

  @doc """
  Generate a save.
  """
  def save_fixture(attrs \\ %{}) do
    user_id_hash = attrs[:user_id_hash] || insert_user().user_id_hash
    level_instance_id = attrs[:level_instance_id] || insert_autogenerated_level_instance().id
    location_id = attrs[:location_id] ||
      insert_player_location(%{user_id_hash: user_id_hash,
        level_instance_id: level_instance_id,
        }).id

    Player.get_location(%{id: location_id})
    |> Player.change_location(%{tile_instance_id: nil})
    |> Repo.update!

    {:ok, save} =
      attrs
      |> Enum.into(%{
        col: 42,
        row: 42,
        state: "player: true",
        user_id_hash: user_id_hash,
        level_instance_id: level_instance_id,
        location_id: location_id
      })
      |> Games.create_save()

    save
  end
end
