defmodule DungeonCrawl.ShippingFixtures do
  @moduledoc """
  This module defines test helpers for creating
  entities via the `DungeonCrawl.Shipping` context.
  """

  import DungeonCrawlWeb.TestHelpers

  @doc """
  Generate a export.
  """
  def export_fixture(attrs \\ %{}) do
    {:ok, export} =
      attrs
      |> Enum.into(%{
        data: "some data",
        file_name: "test.json",
        status: :running,
        dungeon_id: attrs[:dungeon_id] || insert_dungeon(Map.put(attrs, :autogenerated, true)).id,
        user_id: attrs[:user_id] || insert_user().id
      })
      |> DungeonCrawl.Shipping.create_export()

    export
  end

  @doc """
  Generate a import.
  """
  def import_fixture(attrs \\ %{}) do
    {:ok, import} =
      attrs
      |> Enum.into(%{
        data: "some data",
        file_name: "test.json",
        status: :running,
        dungeon_id: attrs[:dungeon_id] || insert_dungeon(Map.put(attrs, :autogenerated, true)).id,
        user_id: attrs[:user_id] || insert_user().id
      })
      |> DungeonCrawl.Shipping.create_import()

    import
  end
end
