defmodule DungeonCrawl.Repo.Migrations.DungeonLevelTableCleanup do
  use Ecto.Migration

  def up do
    alter table(:dungeons) do
      remove :autogenerated
      remove :version
      remove :active
      remove :deleted_at
      remove :previous_version_id
      remove :user_id
    end
  end

  def down do
    raise "no going back, better off trying to reload good dump instead"
    alter table(:dungeons) do
      add :autogenerated, :boolean
      add :version, :integer, default: 1
      add :active, :boolean
      add :deleted_at, :naive_datetime
      add :previous_version_id, references(:dungeons, on_delete: :delete_all)
      add :user_id, references(:users, on_delete: :nilify_all)
    end

    create index(:dungeons, [:user_id])
    create index(:dungeons, [:deleted_at])
    create index(:dungeons, [:active])

    flush()

    execute "UPDATE dungeons SET version = 1, active = true;"
  end
end
