defmodule DungeonCrawl.DungeonInstances.LevelTest do
  use DungeonCrawl.DataCase

  alias DungeonCrawl.Player.Location

  test "on_delete deletes all associated player_locations" do
    level_instance = insert_autogenerated_level_instance()
    player_loc = insert_player_location(%{level_instance_id: level_instance.id})
    assert Repo.preload(level_instance, :locations).locations != []
    assert Repo.delete(level_instance)
    refute Repo.get_by(Location, %{user_id_hash: player_loc.user_id_hash})
    assert Repo.preload(level_instance, :locations).locations == []
  end
end
