defmodule DungeonCrawl.DungeonInstances.MapSetTest do
  use DungeonCrawl.DataCase

  alias DungeonCrawl.Player.Location

  test "on_delete deletes all associated player_locations" do
    instance = insert_autogenerated_dungeon_instance()
    player_loc = insert_player_location(%{map_instance_id: instance.id})
    assert Repo.preload(instance, :locations).locations != []
    assert Repo.delete(instance)
    refute Repo.get_by(Location, %{user_id_hash: player_loc.user_id_hash})
    assert Repo.preload(instance, :locations).locations == []
  end
end
