defmodule DungeonCrawl.DungeonInstances.TileTest do
  use DungeonCrawl.DataCase

  alias DungeonCrawl.Player.Location
  alias DungeonCrawl.DungeonInstances.Tile

  @valid_attrs %{row: 42, col: 42, z_index: 1, tile_template_id: 2, level_instance_id: 1}
  @invalid_attrs %{}

  test "changeset with valid attributes" do
    changeset = Tile.changeset(%Tile{}, @valid_attrs)
    assert changeset.valid?
  end

  test "changeset with invalid attributes" do
    changeset = Tile.changeset(%Tile{}, @invalid_attrs)
    refute changeset.valid?
  end

  test "on_delete deletes all associated player_locations" do
    level_instance = insert_autogenerated_level_instance()
    player_loc = Repo.preload insert_player_location(%{level_instance_id: level_instance.id}), :tile
    assert {:ok, deleted_player_tile} = Repo.delete(player_loc.tile)
    refute Repo.get_by(Location, %{user_id_hash: player_loc.user_id_hash})
    refute Repo.get(Tile, deleted_player_tile.id)
  end
end
